### ISSUE TITLE
Dockerize Application (Go service) & PostgreSQL

### ISSUE THREAD

**Issue by PeteChu** [PeteChu/order-management-service-go#2]
- ID: T2
- Priority: 1
- Story Points: 2
- Title: Dockerize Application (Go service) & PostgreSQL
- Description: Create Dockerfiles for the Go application and a `docker-compose.yml` to run the OMS service and a PostgreSQL database instance locally.
- Dependencies: [T1]
- Parallelizable?: No
- Expected Output: `Dockerfile` for the Go app, `docker-compose.yml` for local development environment.
- Definition of Done:
  • `Dockerfile` for the Go application builds a runnable image.
  • `docker-compose.yml` successfully starts the Go application and a PostgreSQL container.
  • Application can connect to the PostgreSQL instance within Docker network.
  • Basic health check for the Go app in Docker is desirable.
- Deep-Dive Implementation Notes:

  1. Context/rationale: Provides a consistent and reproducible development and testing environment. (Spec Sec 6 for tech stack)
  2. Setup steps: Install Docker and Docker Compose.
  3. Code snippet or pseudo-code:
     `Dockerfile` (multi-stage build for Go):

     ```dockerfile
     # Build stage
     FROM golang:1.21-alpine AS builder
     WORKDIR /app
     COPY go.mod go.sum ./
     RUN go mod download
     COPY . .
     RUN CGO_ENABLED=0 GOOS=linux go build -o /oms_server ./cmd/oms_server

     # Final stage
     FROM alpine:latest
     WORKDIR /root/
     COPY --from=builder /oms_server .
     # Add user, copy config files if any
     EXPOSE 8080 # Or your app's port
     CMD ["./oms_server"]
     ```

     `docker-compose.yml`:

     ```yaml
     version: "3.8"
     services:
       app:
         build: .
         ports:
           - "8080:8080"
         depends_on:
           - db
         environment:
           - DB_HOST=db
           # Other env vars
       db:
         image: postgres:15-alpine
         ports:
           - "5432:5432"
         environment:
           - POSTGRES_USER=omsuser
           - POSTGRES_PASSWORD=omspassword
           - POSTGRES_DB=omsdb
         volumes:
           - postgres_data:/var/lib/postgresql/data
     volumes:
       postgres_data:
     ```

  4. Edge cases/pitfalls: Ensure correct network configuration for app-DB communication in Docker. Manage database credentials securely (use env vars, not hardcoded).
  5. References: Docker documentation, PostgreSQL Docker Hub image.
