### ISSUE TITLE
Basic CI/CD Pipeline Setup (Build, Lint, Test)

### ISSUE THREAD

**Issue by PeteChu** [PeteChu/order-management-service-go#4]
- ID: T4
- Priority: 2
- Story Points: 2
- Title: Basic CI/CD Pipeline Setup (Build, Lint, Test)
- Description: Configure a basic CI pipeline (e.g., GitHub Actions, GitLab CI) that triggers on pushes/merges to build the application, run linters, and execute unit tests (stubs for now).
- Dependencies: [T1]
- Parallelizable?: Yes
- Expected Output: CI configuration file (e.g., `.github/workflows/ci.yml`).
- Definition of Done:
  • CI pipeline runs automatically on code push to main branches.
  • Pipeline executes build, lint, and (stubbed) test stages.
  • Pipeline status (pass/fail) is reported.
- Deep-Dive Implementation Notes:
  1. Context/rationale: Automates quality checks and build process, ensuring code stability.
  2. Setup steps: Choose a CI provider.
  3. Code snippet or pseudo-code (GitHub Actions example):
     ```yaml
     # .github/workflows/ci.yml
     name: OMS CI
     on: [push, pull_request]
     jobs:
       build:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v3
           - name: Set up Go
             uses: actions/setup-go@v3
             with:
               go-version: "1.21"
           - name: Lint
             run: |
               go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
               golangci-lint run ./...
           - name: Build
             run: go build ./cmd/oms_server/...
         # - name: Test (add when tests exist)
         #   run: go test ./...
     ```
  4. Edge cases/pitfalls: Ensure CI environment matches local dev for Go version, dependencies. Cache Go modules for faster builds.
  5. References: GitHub Actions documentation, GitLab CI documentation.
